fix native lazygit editor return

diff --git a/dot_local/bin/executable_lazygit-nvim b/dot_local/bin/executable_lazygit-nvim
--- a/dot_local/bin/executable_lazygit-nvim
+++ b/dot_local/bin/executable_lazygit-nvim
@@ -70,26 +70,42 @@ if [ -z "$server" ]; then
 fi
 
 if [ "$native_nvim" -eq 1 ]; then
+  terminal_buf=$(nvim --headless --server "$server" --remote-expr 'bufnr()' 2>/dev/null) || terminal_buf=
+  log "native terminal buf=${terminal_buf:-<none>}"
+
   case "$mode" in
   edit)
-    nvim --server "$server" --remote-send "q<cmd>sleep 10m<cr>" &&
-      nvim --server "$server" --remote "$1"
+    nvim --headless --server "$server" --remote "$1"
     ;;
   line | wait)
-    nvim --server "$server" --remote-send "q<cmd>sleep 10m<cr>" &&
-      nvim --server "$server" --remote "$2" &&
-      nvim --server "$server" --remote-send "<cmd>$1<cr>"
+    nvim --headless --server "$server" --remote "$2" &&
+      nvim --headless --server "$server" --remote-send "<cmd>$1<cr>"
     ;;
   dir)
-    nvim --server "$server" --remote-send "q<cmd>sleep 10m<cr>" &&
-      nvim --server "$server" --remote "$1"
+    nvim --headless --server "$server" --remote "$1"
     ;;
   *)
     log "unknown native mode=$mode"
     exit 1
     ;;
   esac
-  exit $?
+
+  status=$?
+
+  case "$terminal_buf" in
+  '' | *[!0-9]*)
+    log "skip native terminal close invalid_buf=${terminal_buf:-<none>} status=$status"
+    ;;
+  *)
+    if [ "$status" -eq 0 ]; then
+      nvim --headless --server "$server" --remote-expr \
+        "luaeval('(function() vim.defer_fn(function() local buf = $terminal_buf; if vim.api.nvim_buf_is_valid(buf) and vim.bo[buf].buftype == [[terminal]] then local chan = vim.bo[buf].channel; if chan > 0 then vim.api.nvim_chan_send(chan, [[q]]) end end end, 250); return 0 end)()')" \
+        >/dev/null 2>&1 && log "queued native lazygit quit buf=$terminal_buf" || log "failed native lazygit quit buf=$terminal_buf"
+    fi
+    ;;
+  esac
+
+  exit "$status"
 fi
 
 close_editor_popup() {
